### ISSUE TITLE
Command for changing stream offline message

### ISSUE THREAD

**Issue by marrub--** [dawgeth/CouchBot#10]
I think having a command that sets the message for streams going offline would be useful, especially in multilingual servers. Just something as simple as `!cb message offline "stream is ded :coffin:"` would be nice.

**Comment by dawgeth** [comment]
This is a great recommendation. I've added it to our Trello Board, here: 

https://trello.com/c/Q6bV5IvW/83-new-feature-customizable-offline-messages-for-when-streams-go-offline

This will be worked on tonight - I love it. Thanks!
