### ISSUE TITLE
Un-fixable Problem

### ISSUE THREAD

**Issue by BeardedKitty** [dawgeth/CouchBot#11]
I've been having this problem since a couple updates ago. 

My heart has been aching for you for a while now and the black hole is still there. 

Just kidding xD

Thanks for all the hard work you've been doing and for having such a great bot! He's been configed by me and used in 5 different Discords I am part of!

Keep it up and have a nice day/month/year! <3

**Comment by dawgeth** [comment]
Known issue <3
