### ISSUE TITLE
Support the full urls for platforms

### ISSUE THREAD

**Issue by SUPERCHIEFYT** [dawgeth/CouchBot#124]
🙃

**Comment by MattTheDev** [comment]
Really like this idea. I have a rough implementation in place. Will finalize and get this in ASAP.

**Comment by MattTheDev** [comment]
Testing the implementation of this, and will get it out in the next deployment.

**Comment by MattTheDev** [comment]
Tested - will deploy in the next push. Will announce when deployed in #announcements.
