### ISSUE TITLE
Youtube ID lookup isn't working (no slash commands appear for CB in the server)

### ISSUE THREAD

**Issue by tthornn** [dawgeth/CouchBot#128]
We used to be able to just use !cb ytidlookup [name] and that doesn't work any more.

The slash command in the docs also doesn't work and we apparently can't enable slash commands without the founder of the server, who has been out of the country for months and is busy...

**Comment by SUPERCHIEFYT** [comment]
Hello, The `ytidlookup` command was switched to `/youtube lookup`  however if you don't see the bot's slash commands in the server use https://discord.com/oauth2/authorize?client_id=672994862144159764&scope=applications.commands to authorize the bot with the scope for that server. 
> Anyone with `Manage Server` permission in the server should be able to do that. 

Also for better support join the support server for the bot: https://discord.couch.bot

**Comment by tthornn** [comment]
Thanks; Again I'm just a mod on the server **and I don't seem to have sufficient permissions to update slash commands.** Is there a reason we can't have both the original command and the slash command?

**Comment by MattTheDev** [comment]
Hey @tthornn - I understand the frustration / inability to use the command. I'm actually happy to put it back .. it'll be short lived though. In ~2 months, Discord is making text commands for bots over 100 servers a limited access thing .. anything that can be done via slash command, has to be migrated to them. This is a bummer, I get it. I prefer text commands myself. I'm just going with the flow :(

I'll get it re-added and pushed tonight/tomorrow and let you know when it is done. Sometime in April it'll be removed again in preparation for Discord's change.
