### ISSUE TITLE
Blank stream title sneaks past filters

### ISSUE THREAD

**Issue by InsaneFirebat** [dawgeth/CouchBot#130]
I had another announcement slip through our filter today. Like the previous one, it has a blank stream title. It's only the second time it's happened in two years, so pretty low priority bug.

For reference, I have the filter set to only show "Super Metroid" (game) streams with "GT Classic" or "GTC" in the title. The streams that slipped through were both playing Super Metroid.

**Comment by MattTheDev** [comment]
Working this now .. logic will be...

- If matches and title is != null or whitespace, announce.
- If no match OR title is null or empty, do not announce.

**Comment by MattTheDev** [comment]
`        if (string.IsNullOrEmpty(request.Title.Trim()) &&
            filters.Any(x => x.FilterTypeId == (int)FilterType.Title))
        {
            return false;
        }`

Easy. Peasy. lol

This'll be tested .. and if it passes, will go with the big Slash Command Fix I am preparing..
