### ISSUE TITLE
underscores in twitch urls

### ISSUE THREAD

**Issue by codegotv** [dawgeth/CouchBot#20]
Hello,
First off I want to say thank you very much for creating such a awesome bot.  Our channel uses it everyday and love to see when our memebers go live.

However, I think I did find a bug.  I have a user that his twitch name is https://www.twitch.tv/p3ngin_
The bot notices when he goes live but the link only goes to https://www.twitch.tv/p3ngin  (does not include the underscore at the end of the url)

I was wondering if this could be fixed.

Thanks! - Matt x1622

**Comment by djlax805** [comment]
I'm pretty sure you just need to change up the code found [here](https://github.com/dawgeth/CouchBot/blob/8309de9f24b5018b0a9653bbf8c832b3c4520bcb/src/MTD.CouchBot/Program.cs#L507) to stop replacing underscores with nothing.

**Comment by dawgeth** [comment]
@djlax805 It's 100% this. I was lazy and didn't want to get around Discord's formatting of text. I need to do this still. 

@codegotv I'll put some code in to fix this tonight.

I've got Twitch Teams and Game tracking/announcing done, I just need to test it and Ill push it and this formatting change tomorrow <3

**Comment by djlax805** [comment]
That's awesome, I attempted to clone and setup a C# .Net ENV and give it a go - after some config stuff I'm attempting to learn how to call the Task class inside the Program class - I'm Ruby so there is a lot of syntax I don't understand.  Looking forward to the change, thanks @dawgeth

**Comment by dawgeth** [comment]
Would be nice if I used Unit Tests, wouldn't it @djlax805?! :P

**Comment by dawgeth** [comment]
This was resolved, and is being deployed tonight. Thanks guys :)
