### ISSUE TITLE
Cant add YouTube ID's

### ISSUE THREAD

**Issue by beauhessel** [dawgeth/CouchBot#25]
Currently selfhosting a Couchbot. It'll let me add users from any service accept for YT. When i use, for example "**!cb youtube add UCDRNWWest03PspodMushTDg**", it doesnt return anything, and nothing gets listed. `

I tried adding them manually in the configfile in program data but I didnt know the formatting of the ID's so it would just crash on me. Wondering what the problem is, is it something with the Google API Key?

![screenshot_32](https://user-images.githubusercontent.com/6024073/27652456-1eb95380-5c3c-11e7-8881-ab4bba32238a.png)

**Comment by dawgeth** [comment]
I messaged you on Discord - can you provide me your BotSettings.json and the file in the Guild folder that correlates with the server you're on? This would help finding the problem. I am almost 100% sure I know the issue - Once I have those, we'll iron it out.

**Comment by dawgeth** [comment]
Had @beauhessel enable the YouTube Data API and all was good!
