### ISSUE TITLE
[Self Host Bot] Bot starts running, checks services, and functions - but never shows Online in Discord.

### ISSUE THREAD

**Issue by TheBanHammer** [dawgeth/CouchBot#26]
Bot is starting up successfully but not showing as online/responding to Discord.

**Comment by dawgeth** [comment]
We're discussing in Discord atm :3 Will post update when completed.

**Comment by dawgeth** [comment]
Issue occurs over multiple Discord tokens. No errors being thrown. Bot starts and starts checking services .. but it never logs into Discord.

We'll continue digging through this.

**Comment by dawgeth** [comment]
Working with another user, we fixed this by recreating the bot in the Discord developers console. It seemed to be a problem with his bot that was created in the panel. 

discordapp.com/developers/applications/me

Can you try this @TheBanHammer - It seemed to have fixed his issue.

**Comment by dawgeth** [comment]
Appears to be OS related. Windows 7, Windows Server 2008 R2 both have the same behavior. 

Windows 8, 10, Server 2012, all no issue.

Need to get my hands on a Windows 7 VM to test why this is a thing...

**Comment by dawgeth** [comment]
No response back. Closing as I've fixed this in most cases.
