### ISSUE TITLE
Bot not announcing random people

### ISSUE THREAD

**Issue by itslumen** [dawgeth/CouchBot#32]
Hey Dawgeth! I'm having an issue where couchbot isn't announcing certain people going live, but it's over all the discords they're in that use couchbot. It seems to only be happening for mixer users as far as I know, and only random, certain people. Just wanted to leave a heads up! Thank you so much for couchbot!

**Comment by dawgeth** [comment]
Happy to provide him :)

Could you verify times that you're seeing this? Have had a spout of downtime over the past probably week with the bot having a few issues.

**Comment by dawgeth** [comment]
Closing. If user comes back, please provide additional info requested above.
