### ISSUE TITLE
@ Mention with twitch feed & Deleting Old Live Post

### ISSUE THREAD

**Issue by GreenPandaTV** [dawgeth/CouchBot#35]
I'm trying to get the twitch feed to use the @everyone so it shows as a notification for people.

Also when I set the setting !cb config deleteoffline to True it dose not delete the old post when i close OBS.

**Comment by dawgeth** [comment]
Nothing with things other than Mixer are instant. Twitch, which I believe you use, doesn't offer up the ability to listen for events to happen - I can only poll for changes on channels. When Im checking over 6000 channels - that takes time. The cleanup process we talked about last night - thats when the deleting happens. Did it clean up eventually? 

As for the @ everyone tag on Twitch Feed messages - I can put in an enhancement request for this, but it's currently not part of its functionality. I could see how it would be nice to have though.

**Comment by GreenPandaTV** [comment]
It did clean up eventually!

Yes this @everyone would be really nice to have!!

**Comment by dawgeth** [comment]
Created enhancement request #36 - Closing this one. Will resolve it over there.
