### ISSUE TITLE
Youtube live event not announced

### ISSUE THREAD

**Issue by k3nnny** [dawgeth/CouchBot#42]
Hey!

I added couchbot to my discord server. Works nice except one thing.
I always making live event not "stream now". Somehow it's not announced on the discord feed however when the stream ends the vod is posted as uploaded video so it's detecting my channel.
Any suggestion? Or it's not working with events just stream now?

edit: this is the current config:
- Owner Go Live Channel: general
- Owner Published Channel: general
- Owner Twitch Channel Feed Channel: Not Set
- Go Live Channel: general
- Published Channel: general
- Greetings Channel: Not Set
- Allow @ Role: True
- Allow Thumbnails: True
- Allow Greetings: True
- Allow Goodbyes: False
- Allow Live Content: True
- Allow Published Content: True
- Allow Owner Twitch Channel Feed: False
- Use Text Announcements: False
- Use YTG URLS For VOD Content: False
- Live Message: Stream start!
- Published Message: New vid!
- Greeting Message: HF!
- Goodbye Message: Default
- Stream Offline Message: Default
- Mention Role: Everyone
- Time Zone Offset: 0

Regards,
Matthew

**Comment by dawgeth** [comment]
I'd be interested to know your server name so I can look up the config on my end. Events and Stream Now are essentially the same thing on the back end - no real distinction - and I've used both in testing/recently and had no issue.

**Comment by k3nnny** [comment]
Do you need a simple invite? Also probably the bot was offline when I finished the stream because now it didn't posted the finished vod either.

**Comment by dawgeth** [comment]
Yeah, I'm completely rewriting him. His data structure wasn't scalable to the numbers we've grown to. He goes offline every so often for an issue I could bandaid, but I'd rather just rewrite.

Just the name of the server/your discord name should suffice.

**Comment by k3nnny** [comment]
kEn's homeland is the name
Yeah I noticed multiple disconnects but it's okay and really appreciate your work :)

**Comment by lieblingkira** [comment]
My Couchbot is also refusing to announce my YouTube streamers and it seems like it won't announce Picarto either. 

Also this might be unrelated but I also can't check the live message for Picarto users.

My server is called [Dauntless Unofficial Streaming Team](https://discord.gg/fdam4pu)

**Comment by dawgeth** [comment]
@lieblingkira Your config is wrong :) Hope in http://discord.couchbot.io - mention this post, and I can get you setup and fixed!!

**Comment by dawgeth** [comment]
@k3nnny I see nothing wrong :( Join the discord listed above - and let's work through this :)

**Comment by k3nnny** [comment]
I had 3 streams at the weekend and none of them announced in the feed. The vods are posted as video thats working fine. I'll join your server soon :)

**Comment by RazCallahan** [comment]
Have same problem. When i removed all files from "live/youtube" folder it worked fine one more time. Cleaning folder before stream is a questionable solution, but it works :D 
p.s. sorry for crappy english.

**Comment by dawgeth** [comment]
@RazCallahan I assume this is in the Self Host Bot?

@k3nnny Drop by the Discord, I have some further questions for you.
