### ISSUE TITLE
Option to change mention to "here"

### ISSUE THREAD

**Issue by SinaCutie** [dawgeth/CouchBot#43]
Would it be possible to have an option to let the mention use @here instead of @everyone ? I am unable to find an option for this.

Thanks! <3

**Comment by dawgeth** [comment]
Got this done. Deploying now.

**Comment by wcphart** [comment]
Is this the config mentionrole command? I cant get it to work correctly if so.

**Comment by dawgeth** [comment]
Try !cb config mentionrole here  ... it should grab it.
