### ISSUE TITLE
Exception: Websocket protocol not supported on this platform

### ISSUE THREAD

**Issue by InsaneFirebat** [dawgeth/CouchBot#5]
After following all of the setup instructions including .net core installation, I hit an error and then "dotnet" stops responding according to Windows. Logs at https://pastebin.com/RwxAh5nc

**Comment by dawgeth** [comment]
@InsaneFirebat 

I learn something new every day. Looks like Websockets are not compatible with Windows 7.

Per: http://stackoverflow.com/questions/11039438/using-websocket-on-windows7

I'll see if there is a workaround for this for you.
