### ISSUE TITLE
Feature Request: Pull Mod/Modpacks/Texture Packs from Curse

### ISSUE THREAD

**Issue by Dolinmyster** [dawgeth/CouchBot#51]
Hey there!

We added your bot to a large Discord server and we have a lot of people in there that are Mod Devs and Modpack Makers for Minecraft. I was curious if it would be possible to make Couchbot be able to pull updates on peoples mods and or modpacks from Curse? So if they push an update it will post it just like with Streams and Videos. 

~Dolin

P.S. I know there's bots that do this, but maybe also pull from GitHub as well.

**Comment by dawgeth** [comment]
Heya Dolin! I think this would be a better fit in another bot. CouchBot really is trying to stay with the "Streamer/Content Creator" aligned functionality. A lot of bots out there try to add every. single. thing. in the world. and forget what their core purpose is. I'm trying to keep a clear focus on ol' Couchy.

HOWEVER! This is a great idea :) Which bot pulls Curse info? I'd be interested.. I know Yappy! does GitHub solely.

**Comment by Dolinmyster** [comment]
Thanks for the response! I figured since I mean mods are sort of a form of "content" that it would fit. But it's your bot and I understand where you stand. I'm not sure if currently any bots do pull from Curse, but I can do some digging and see what I can find, I do know that there are some that do GitHub requests already. Thanks for taking a look!
