### ISSUE TITLE
greeting announcements seems to be broken

### ISSUE THREAD

**Issue by crossfire151** [dawgeth/CouchBot#55]
I noticed the greetings seems to be repeating the same message over and over with the same previous name when a new member joins the server.

Screenshot provided.

![untitled](https://user-images.githubusercontent.com/13416803/30513643-8b5cc9ee-9afe-11e7-8806-73a9063843dd.png)

my !cb greetings message:
!cb greetings set "Welcome %USER%!, thank you for joining. Feel free to take a look around and/or join in. Please take a look at #rules before you begin, to make yourself aware of the rules and to help keep the community at peace! %NEWLINE% Your owner is @Crossfire151. %NEWLINE% Your moderators are: @Fargos (Moy) (Moy) and @Dkz420. %NEWLINE% If you have any problems please speak to the owner you a Moderator and they will be happy to help! %NEWLINE% %NEWLINE% Any suggestions/ feedback? leave them over here: #suggestions."

I hope this helps,

thanks,
crossfire151

**Comment by dawgeth** [comment]
I am unable to recreate this problem @crossfire151 ... Maybe I fixed it in a release? Can you confirm?
