### ISSUE TITLE
Self Host not supporting channel categories

### ISSUE THREAD

**Issue by Ir0ns1de** [dawgeth/CouchBot#56]
Issue: Bot not responding on server with categories

Expected outcome: Bot should...respond and announce.

Steps taken to reproduce:

1. Invited bot to new server without categories, verified it works there. 
2. Created Category and tested in channel under category - works
3. Restarted bot and tested again in channel under category - failed
4. Removed category and restarted - Works

Edit: Should mention I provided admin rights to the bot in order to eliminate permissions issues.

**Comment by chrisowens** [comment]
Can confirm I'm having the same issue.

**Comment by dawgeth** [comment]
Self host bot stopped being supported months ago. I have no time to maintain 2 codebases - and with our API access to a special YouTube API - YouTube would be busted for anyone besides me. 

I've had 2 patrons ask that I look into it. I'll post details about it on the support Discord if/when I get to it. There is 0 ETA. 

Closing this for now.
