### ISSUE TITLE
Forgets Streamers

### ISSUE THREAD

**Issue by mrpaden** [dawgeth/CouchBot#6]
Greetings. I am having a problem with my couchbot on my stream team discord server. We are a small team so we only have 3-4 people that the bot needs to post for. At first, it announces when those streamers go live no problem. However, it seems to eventually just stop working. There doesn't seem to be a rhyme or reason to it. It will stop working for one streamer, and continue working for another. The only way to fix it it seems is to remove the streamer from the list and then readd them. After this, it works fine for a few days and then the problem repeats. Very odd and any help to prevent this from continuing would be appreciated. Here's the config list as requested.

# Tom Foolery Configuration Settings
- Announcements Channel: Not Set
- Go Live Channel: going-live
- Greetings Channel: entrances-and-exits
- Published/VOD Channel: Not Set
- Allow @ Everyone: False
- Allow Thumbnails: True
- Allow Broadcast Others: True
- Allow Greetings: True
- Allow Goodbyes: True
- Allow VOD Content: False
- Allow Others VOD Content: False
- Use Text Announcements: False
- Use YTG URLS For VOD Content: False
- Use Whitelist: True
- Current Whitelist: Empty
- Live Message: Default
- Published Message: Default
- Greeting Message: Welcome to the server, %USER%
- Goodbye Message: %USER% has left the server.
- Mention Role: Everyone
- Time Zone Offset: 0
---- [Unused At The Moment] ----
- Broadcast Sub Goals: False

**Comment by dawgeth** [comment]
That's a weird one! What platform is it @mrpaden? Twitch, Beam, YouTube, Hitbox? Also, can you give me names of the streamers in question (channel IDs or names).

**Comment by mrpaden** [comment]
All streamers are on Beam. Main ones I've noticed issue with is myself (same name MRPaden) and Banewreaker. 

# Server Configured Channels
- YouTube Gaming: 
- Twitch: 
- Beam: mrpaden, banewreaker, gamingargoyle, snipe86k, mindscape
- Hitbox:

**Comment by dawgeth** [comment]
If the Beam constellation connection is offline - it wont announce. Im going out on a limb and saying that's your issue. It's subscribing to events from everyone on bot startup - and it 100% doesn't forget streamers :) It saves your Beam ID, resubs on startup .. but if Beam/Constellation has an issue .. it disconnects .. and it needs to re-establish that connection. 

Once I restart the bot, it then resubscribes to the events from the people in the list. Constellation is up more and more now that their instability issues are solid .. but can you try something for me? Next time you see someone go live.. and the bot doesnt announce them.. type !cb beam status .. and let me know what it says :) I wrote re-connect logic.. it failed. Doesnt work. So Im ironing out why.

**Comment by dawgeth** [comment]
I've added additional reconnect logic - I've validated it subscribes to the channel above accounts on launch of the Bot. So there is no issue there. There should be 0 need to remove-readd streamers. I will monitor the Constellation issues and validate my reconnect logic. If it continues - please re-open this issue. 

Thanks so much for being patient with our special lil bot <3 :P
