### ISSUE TITLE
CouchBot offline?

### ISSUE THREAD

**Issue by Veicoc** [dawgeth/CouchBot#65]
what happend? CouchBot just got offline and cant respond for any command?

**Comment by dawgeth** [comment]
Was due to a change I deployed last night in preparation of bot transition Sunday night. Up and running. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Veicoc** [comment]
ok cool, just for note, ur bot is going offline and online all the time,
just asking myself can i trust it?

so annoying cause was going to to try new commands and just then it's going
offline...



2017-11-01 14:53 GMT+02:00 dawgeth <notifications@github.com>:
