### ISSUE TITLE
Bot not announcing after it went down

### ISSUE THREAD

**Issue by XKPlayzYT** [dawgeth/CouchBot#7]
The bot won't announce the streamers I've added anymore. What do I need to do so I can make them announce again? It only announces for Twitch. Not Beam at all. For YouTube Gaming I don't know yet.

# The X-Stoppables Configuration Settings
- Announcements Channel: Not Set
- Go Live Channel: promotions
- Greetings Channel: Not Set
- Published/VOD Channel: Not Set
- Allow @ Everyone: False
- Allow Thumbnails: False
- Allow Broadcast Others: True
- Allow Greetings: False
- Allow Goodbyes: False
- Allow VOD Content: False
- Allow Others VOD Content: False
- Use Text Announcements: False
- Use YTG URLS For VOD Content: False
- Use Whitelist: False
- Current Whitelist: Empty
- Live Message: %TITLE% | %GAME% | %URL%
- Published Message: Someone has gone live!
- Greeting Message: Default
- Goodbye Message: Default
- Mention Role: Everyone
- Time Zone Offset: 0
---- [Unused At The Moment] ----
- Broadcast Sub Goals: False

**Comment by GamertagIsAnt** [comment]
Same here it only works for a Myself and a one other streamer(who isn't in my Discord) but I've added several to the list, I wonder if they have to be part of your discord server.

**Comment by Soulless512** [comment]
I too am having the same issue. none of the people that I have set up for beam are showing up, except for a select few. here is my configuration 
- Announcements Channel: Not Set
- Go Live Channel: streampromote
- Greetings Channel: rules
- Published/VOD Channel: Not Set
- Allow @ Everyone: True
- Allow Thumbnails: True
- Allow Broadcast Others: True
- Allow Greetings: True
- Allow Goodbyes: True
- Allow VOD Content: False
- Allow Others VOD Content: False
- Use Text Announcements: False
- Use YTG URLS For VOD Content: False
- Use Whitelist: False
- Current Whitelist: Empty
- Live Message: Default
- Published Message: Default
- Greeting Message: Welcome to The Soul Army!!!
- Goodbye Message: Farewell
- Mention Role: Everyone
- Time Zone Offset: -5
---- [Unused At The Moment] ----
- Broadcast Sub Goals: False

**Comment by dawgeth** [comment]
Same issue, I imagine, across the board for you guys AND in the other issue that's along these lines.

Constellation and Beam as a whole are getting hammered. There is reconnect logic for the websocket connection to Constellation - but it clearly has issues :) 

I can say, 100%, that it's not skipping people - it's probably just that the Constellation connection dropped.

**Comment by dawgeth** [comment]
I've added additional reconnect logic - I've validated it subscribes to the channel above accounts on launch of the Bot. So there is no issue there. There should be 0 need to remove-readd streamers. I will monitor the Constellation issues and validate my reconnect logic. If it continues - please re-open this issue. 

Thanks so much for being patient with our special lil bot <3 :P
