### ISSUE TITLE
Beam stream issue

### ISSUE THREAD

**Issue by GamerJameo** [dawgeth/CouchBot#8]
Hey, since using the self hosted bot i have been having issues with the bot announcing beam streams.... it seems after a few hours of having the bot running it will only announce twitch streams and not beam

**Comment by dawgeth** [comment]
Issue is with reconnect logic - even in current live bot, he doesn't reconnect.

Personally, I'd use another bot. Going to be abandoning CouchBot once someone either takes over running him or I shutter the doors.

https://forums.beam.pro/topic/2739/m8-bot-he-s-your-best-m8-for-beam-discord is a great option. Dude is a great dev.
